{
    'name': 'Archer Employee Requests',
    'version': '15.0.0',
    'summary': 'HR Improvements',
    'description': '',
    'category': 'hr',
    'author': "Archer Solutions",
    'website': "http://archer.solutions",
    'license': 'OPL-1',
    'depends': ['base_address_city', 'employee_penalty','hr', 'hr_expense', 'archer_base_hr', 'archer_project_custom', 'archer_hr_custom', 'web_domain_field'],
    'data': [
        'data/sequence.xml',
        'data/residency_data.xml',
        'data/residency_issuance_workflow.xml',
        'data/visa_exit_re_entry_workflow.xml',
        'data/travel_ticket_workflow.xml',
        'data/business_trip_workflow.xml',
        'data/leave_request_workflow.xml',
        'data/expense_request_workflow.xml',
        'data/residency_job_title_workflow.xml',
        'data/visit_visa_workflow.xml',
        'data/salary_transfer_workflow.xml',
        'data/resignation_workflow.xml',
        'data/benefit_workflow.xml',
        'data/loan_advance_workflow.xml',
        'data/po_expense_workflow.xml',
        'data/salary_confirmation_letter_workflow.xml',
        'data/salary_identification_letter_workflow.xml',
        'security/ir.model.access.csv',
        'views/view_residency_issuance.xml',
        'views/view_residency.xml',
        'views/residency_job_title_views.xml',
        'views/view_expense_request.xml',
        'views/hr_expense_views.xml',
        'views/view_visit_visa.xml',
        'views/view_exit_re_entry.xml',
        'views/view_salary_transfer.xml',
        'views/business_trip_views.xml',
        'views/view_loan.xml',
        'views/view_travel_tickets.xml',
        'views/leave_request_views.xml',
        'views/hr_employee.xml',
        'views/resignation_views.xml',
        'views/benefit_views.xml',
        'views/po_expense_views.xml',
        'views/salary_confirmation_letter_views.xml',
        'views/salary_identification_letter_views.xml',
        'views/employee_request_menu.xml',
        'reports/salary_identification_report.xml',

    ],
    'demo': [],
    'installable': True,
    'auto_install': False
}
