from . import hr_employee
from . import residency
from . import residency_issuance
from . import document
from . import approval_reject_request
from . import expense_request
from . import visit_visa
from . import exit_re_entry_visa
from . import salary_transfer
from . import loan
from . import travel_tickets
from . import residency_job_title
from . import business_trip
from . import hr_expense
from . import leave_request
from . import resignation
from . import benefit
from . import po_expense
from . import salary_confirmation_letter
from . import salary_identification_letter
from . import fmc_helper
